# Generated by Django 3.2.3 on 2021-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=15)),
                ('datestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
